{{- if and .Values.chromeNode.enabled .Values.autoscaling.enabled (eq .Values.autoscaling.scalingType "job") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ template "seleniumGrid.chromeNode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: &chrome_node_labels
    app: selenium-chrome-node
    app.kubernetes.io/name: selenium-chrome-node
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.chromeNode.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  maxReplicaCount: {{ .Values.chromeNode.maxReplicaCount }}
  {{- with .Values.chromeNode.scaledJobOptions }}
    {{ toYaml . | nindent 2 }}
  {{- end }}
  triggers:
    - type: selenium-grid
    {{- with .Values.chromeNode.hpa }}
      metadata: {{- toYaml . | nindent 8 }}
    {{- end }}
  jobTargetRef:
    parallelism: 1
    completions: 1
    backoffLimit: 0
    template:
      metadata:
        labels: *chrome_node_labels
        annotations:
          checksum/event-bus-configmap: {{ include (print $.Template.BasePath "/event-bus-configmap.yaml") . | sha256sum }}
          {{- with .Values.chromeNode.annotations }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        restartPolicy: Never
      {{- with .Values.chromeNode.hostAliases }}
        hostAliases: {{ toYaml . | nindent 10 }}
      {{- end }}
        containers:
          - name: selenium-chrome-node
            {{- $imageTag := default .Values.global.seleniumGrid.nodesImageTag .Values.chromeNode.imageTag }}
            image: {{ printf "%s:%s" .Values.chromeNode.imageName $imageTag }}
            imagePullPolicy: {{ .Values.chromeNode.imagePullPolicy }}
            env:
            - name: DRAIN_AFTER_SESSION_COUNT
              value: "1"
          {{- with .Values.chromeNode.extraEnvironmentVariables }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
            envFrom:
              - configMapRef:
                  name: {{ .Values.busConfigMap.name }}
              {{- with .Values.chromeNode.extraEnvFrom }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
          {{- if gt (len .Values.chromeNode.ports) 0 }}
            ports:
            {{- range .Values.chromeNode.ports }}
              - containerPort: {{ . }}
                protocol: TCP
            {{- end }}
          {{- end }}
            volumeMounts:
              - name: dshm
                mountPath: /dev/shm
            {{- if .Values.chromeNode.extraVolumeMounts }}
              {{- toYaml .Values.chromeNode.extraVolumeMounts | nindent 14 }}
            {{- end }}
          {{- with .Values.chromeNode.resources }}
            resources: {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.chromeNode.lifecycle }}
            lifecycle: {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.chromeNode.startupProbe }}
            startupProbe: {{- toYaml . | nindent 14 }}
          {{- end }}
      {{- if or .Values.global.seleniumGrid.imagePullSecret .Values.chromeNode.imagePullSecret }}
        imagePullSecrets:
          - name: {{ default .Values.global.seleniumGrid.imagePullSecret .Values.chromeNode.imagePullSecret }}
      {{- end }}
      {{- with .Values.chromeNode.nodeSelector }}
        nodeSelector: {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.chromeNode.tolerations }}
        tolerations:
          {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chromeNode.priorityClassName }}
        priorityClassName: {{ . }}
      {{- end }}
        terminationGracePeriodSeconds: {{ .Values.chromeNode.terminationGracePeriodSeconds }}
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: {{ default "1Gi" .Values.chromeNode.dshmVolumeSizeLimit }}
        {{- if .Values.chromeNode.extraVolumes }}
          {{ toYaml .Values.chromeNode.extraVolumes | nindent 10 }}
        {{- end }}
{{- end }}
