apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/helm/release.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
        - image: ghcr.io/jenkins-x/jx-boot:3.10.85
          name: chart-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            jx gitops yset -p version -v "$VERSION" -f ./charts/selenium-grid/Chart.yaml
            yq e -i '.sources = ((.sources // []) + "'$REPO_URL'" | unique)' ./charts/selenium-grid/Chart.yaml
        - name: promote-changelog
          resources: {}
        - name: promote-helm-release
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
